// <auto-generated />
using System;
using EstudoPlanner.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstudoPlanner.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520225507_UpdateEntities")]
    partial class UpdateEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("EstudoPlanner.Domain.Models.ScheduleModel", b =>
                {
                    b.Property<Guid>("IdSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdStudyPlan")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSchedule");

                    b.HasIndex("IdStudyPlan");

                    b.ToTable("tb_Schedules", (string)null);
                });

            modelBuilder.Entity("EstudoPlanner.Domain.Models.StudyPlanModel", b =>
                {
                    b.Property<Guid>("IdStudyPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdStudyPlan");

                    b.HasIndex("IdUser");

                    b.ToTable("tb_StudyPlans", (string)null);
                });

            modelBuilder.Entity("EstudoPlanner.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tb_Users", (string)null);
                });

            modelBuilder.Entity("EstudoPlanner.Domain.Models.ScheduleModel", b =>
                {
                    b.HasOne("EstudoPlanner.Domain.Models.StudyPlanModel", "StudyPlan")
                        .WithMany("Schedules")
                        .HasForeignKey("IdStudyPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("EstudoPlanner.Domain.Models.StudyPlanModel", b =>
                {
                    b.HasOne("EstudoPlanner.Domain.Models.UserModel", "User")
                        .WithMany("StudyPlans")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EstudoPlanner.Domain.Models.StudyPlanModel", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("EstudoPlanner.Domain.Models.UserModel", b =>
                {
                    b.Navigation("StudyPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
